language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - pip install -e .[tests]
script:
    - py.test
    - pynt LICENSE &
    - gynt LICENSE /dev/null
    - python setup.py egg_info -bdev sdist --formats gztar
